### ISSUE TITLE
Stuck while downloading audio

### ISSUE THREAD

**Issue by code-rgb** [iytdl/iytdl#10]
Link: https://www.youtube.com/watch?v=IgQEefhmPXI 

![Screenshot_20210911-005304~2](https://user-images.githubusercontent.com/62891774/132906587-91335920-0ad2-4314-9e4f-a1cd4c5b9dea.png)

**Comment by code-rgb** [comment]
Traceback
```
2021-09-10T19:20:19.448796+00:00 app[worker.1]: ValueError: invalid literal for int() with base 10: '320[filesize<?1950M]'
2021-09-10T19:20:19.455996+00:00 app[worker.1]: [ 10.09.21 07:20:19 PM ]  YoutubeDL    |  ERROR    |  None
2021-09-10T19:20:19.455998+00:00 app[worker.1]: Traceback (most recent call last):
2021-09-10T19:20:19.455998+00:00 app[worker.1]:   File "/app/droid/core/base_decorator.py", line 37, in wrapper
2021-09-10T19:20:19.455999+00:00 app[worker.1]:     out = await func(mod, context)
2021-09-10T19:20:19.455999+00:00 app[worker.1]:   File "/app/droid/modules/youtube.py", line 125, in yt_download
2021-09-10T19:20:19.456000+00:00 app[worker.1]:     if key := await self.ytdl.download(
2021-09-10T19:20:19.456000+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/iytdl/downloader.py", line 190, in download
2021-09-10T19:20:19.456001+00:00 app[worker.1]:     raise DownloadFailedError(str(out))
2021-09-10T19:20:19.456001+00:00 app[worker.1]: iytdl.exceptions.DownloadFailedError: None
```
